name: deepcrunch-environment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - plotly
dependencies:
  - python=3.10
  - pip=23.1.2

# build tools
  - make
  - setuptools=68.0.0

# third party packages - deep learning
  - pytorch=1.11

# third party packages - onnx
  - onnx
  - onnxconverter-common

# third party packages - distributed computing
  - pytest
  - pytest-cov

# PIP packages
  - pip:
    - onnxruntime-gpu==1.14
