name: deepcrunch-environment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - plotly
dependencies:
  - python=3.10
  - pip=23.1.2

# build tools
  - make
  - setuptools=68.0.0

# third party packages - deep learning
  - pytorch

<<<<<<< Updated upstream
# third party packages - onnx
  - onnx
  - onnxruntime
  - onnxconverter-common

  - pip:
    # third party packages - distributed computing
    - pytest-cov
=======
<<<<<<< Updated upstream
  - pip:
# third party packages - distributed computing
    - ray[air]
    - pytest-cov
=======
# third party packages - onnx
  - onnx
  - onnxruntime
  - onnxconverter-common

# third party packages - distributed computing
  - pytest
  - pytest-cov

  - sphinx
  - pydata-sphinx-theme
>>>>>>> Stashed changes
>>>>>>> Stashed changes
