name: deepcrunch-environment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - plotly
dependencies:
  - python=3.10
  - pip=23.1.2

# linting and formatting
  - black=23.3.0
  - flake8
  - autopep8
  - isort

# build tools
  - make
  - setuptools=68.0.0

# third party packages - data science
  - numpy
  - jupyterlab
  - plotly_express
  - wandb

# third party packages - deep learning
  - pytorch

  - pip:
# third party packages - distributed computing
    - ray[air]