name: deepcrunch-environment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - plotly
dependencies:
  - python=3.10
  - pip=23.1.2

# build tools
  - make
  - setuptools=68.0.0

# third party packages - deep learning
  - pytorch

# third party packages - onnx
  - onnx
  - onnxruntime
  - onnxconverter-common

  - pip:
    # third party packages - distributed computing
    - pytest-cov
